# Generated by Django 3.2.13 on 2022-07-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20220702_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ava',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
