# Generated by Django 3.2.13 on 2022-07-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='torrent',
            field=models.FileField(null=True, upload_to='torrent'),
        ),
    ]
