# Generated by Django 4.0.5 on 2022-07-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_torrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Serials'), (2, 'Films'), (1, 'Anime')], null=True, verbose_name='type'),
        ),
    ]
