# Generated by Django 4.0.5 on 2022-07-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Фильм'), (3, 'Сериал'), (1, 'Аниме')], null=True, verbose_name='type'),
        ),
    ]
