# Generated by Django 4.0.5 on 2022-07-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Аниме'), (2, 'Фильм'), (3, 'Сериал')], null=True, verbose_name='type'),
        ),
    ]
